name: bike_demand_prediction
services:
  streamlit:
    build: docker/streamlit
    image: aifakhri/bike-sharing-prediction
    container_name: streamlit_frontend
    depends_on:
      - api
    ports:
      - 8051:8051
    volumes:
      - ./:/home/
  api:
    build: docker/api
    image: aifakhri/bike-sharing-prediction
    container_name: api_backend
    ports:
      - 8080:8080
    volumes:
      - ./:/home/